version: '3'
services:
  mqtt:
    container_name: mqtt_agent
    image: eclipse-mosquitto
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - "8883:8883"
      - "127.0.0.1:1883:1883"
    restart: unless-stopped

